name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # 'main' ブランチへのプッシュ時に実行 (または 'master' など)
  # pull_request セクションを削除

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # 実行環境
    env: # ★ 環境変数を設定
      # クライアントサイドFirebase SDK用 (もし .env.local をリポジトリに含めない場合)
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
      # Firebase Admin SDK用
      GOOGLE_APPLICATION_CREDENTIALS_JSON_STRING: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_STRING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # リポジトリをチェックアウト

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # package.jsonのengines.nodeと合わせる
          cache: 'npm' # または 'yarn'

      - name: Install dependencies
        run: npm ci # npm install --frozen-lockfile と同じ、より安全

      - name: Build Next.js application
        run: npm run build # Next.jsアプリをビルド (outディレクトリが生成される)

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          # ステップレベルで環境変数を設定し、firebase deploy コマンドが参照できるようにする
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account-key.json
        run: |
          echo "Firebase CLI Version:"
          firebase --version

          echo "Creating service account key file..."
          # printf を使用して、より安全にファイルへ書き出す
          printf '%s' "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_STRING }}" > ${{ github.workspace }}/service-account-key.json
          
          echo "Verifying service account key file (first 50 characters to check if it's not empty/malformed):"
          head -c 50 ${{ github.workspace }}/service-account-key.json
          echo # For a new line in the log

          echo "Attempting to deploy to Firebase Hosting using GOOGLE_APPLICATION_CREDENTIALS..."
          # GOOGLE_APPLICATION_CREDENTIALS 環境変数が設定されていれば、CLIは自動的にそれを読み込む
          # --debug オプションを追加して詳細なログを出力
          firebase deploy --only hosting --project krbapps --force --debug
          
          echo "Cleaning up service account key file..."
          rm ${{ github.workspace }}/service-account-key.json